version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - "> 13.1.1, < 14"
  - dependency-name: webtorrent
    versions:
    - 0.116.2
    - 0.117.0
